#170009281 Fixed backed issues
key-joshua/broadcaster-andela-cycle-13 pull request #71
Opened 2019-11-28 03:13 UTC by key-joshua

## WHAT DOES THIS PR DO?

- I have removed all the data I had in a data structure.
- I have replaced regex algorithms with the Joi library.
- I have removed codes of taking user information in each single file with one method.
- I have replaced calling dotenv library in each single file with calling in root-file of app.
- I have changed the insensitive way I used to declaring with a proper way like going with camelcase rule.
- I have reduced duplication codes like variables, functions as I suggested with maintainability before.

## DESCRIPTION OF TASK TO BE COMPLETED?

During in the completion of this work I have replaced regex algorithms I was used before with Joi library where also I have removed all data I had in data structure. Again I have removed codes of taking user information in each single file then now am using one method to do this action. Therefore I have stopped calling dotenv library and configure it in every single file 
then now am calling this library and configuring it in the root-file of the app. the same time I have changed the insensitive way I used to declaring variables 
and methods with proper way like following camelcase rule. And In the end I have reduced duplication codes like variables, functions as I suggested with maintainability before.

## HOW SHOULD THIS BE MANUALLY TESTED?

####  The way this will be tested:

- Users should clone this repository into his/her machine.
- Users should run ```npm run server``` command to start the server.
- User should have to open postman by the way of testing every single endpoint.
- At the same time, Users should go with README file, because there will have a Heroku API documentation link.
- Then users should use this  Heroku API documentation link to testing every single endpoint online directly.

## ANY BACKGROUND CONTEXT YOU  WANT TO PROVIDE?

- The context was all about NODEJS with LIBRARIES.

## WHAT ARE THE RELEVANT PIVOTAL TRACKER STORIES?
- [Bug: Fixed backed issues](https://www.pivotaltracker.com/story/show/170009281)

#### Screenshots (if appropriate)

- Before remove data in data structure
![data structure](https://user-images.githubusercontent.com/38179232/69772580-fa48d600-1198-11ea-8b52-5186e68e638f.PNG)

- After remove data in data structure
![data structure after](https://user-images.githubusercontent.com/38179232/69772633-27958400-1199-11ea-8dc8-79ee3701943a.PNG)

- Before remove regex algorithms
![duplication](https://user-images.githubusercontent.com/38179232/69772834-af7b8e00-1199-11ea-92ef-13a379681c70.PNG)

- After removing regex algorithms
![valid after](https://user-images.githubusercontent.com/38179232/69772881-de91ff80-1199-11ea-8dae-7881719a5173.PNG)

- Before removed dotenv library and configuration
![valids](https://user-images.githubusercontent.com/38179232/69773161-b35be000-119a-11ea-9d01-0c428e049aa8.PNG)

- After removing dotenv library and configuration
![take info after](https://user-images.githubusercontent.com/38179232/69773323-33824580-119b-11ea-98b0-4042e744a010.PNG)

- Before removed codes of taking user information
![valids](https://user-images.githubusercontent.com/38179232/69773012-48120e00-119a-11ea-9806-cfd470557597.PNG)

- After removing codes of taking user information
![take info after](https://user-images.githubusercontent.com/38179232/69773058-6ed04480-119a-11ea-9852-2a0bac6b5edb.PNG)

- Before change insensitive declaration
![declaring](https://user-images.githubusercontent.com/38179232/69773597-f074a200-119b-11ea-892f-4e1407ed7775.PNG)

- After change insensitive declaration
![declaring after](https://user-images.githubusercontent.com/38179232/69773633-04b89f00-119c-11ea-91ab-0ce68d4aaa3e.PNG)

- Before reducing codes
![duplication](https://user-images.githubusercontent.com/38179232/69773707-3c274b80-119c-11ea-9603-8c5573237464.PNG)

- After reducing codes
![duplication after](https://user-images.githubusercontent.com/38179232/69773732-4f3a1b80-119c-11ea-80f7-18e70263da4b.PNG)

-Before testing all endpoints
![testing](https://user-images.githubusercontent.com/38179232/69773761-65e07280-119c-11ea-8c2b-0bbb989f52f8.PNG)

- After Testing all endpoint
![testing after](https://user-images.githubusercontent.com/38179232/69773793-7bee3300-119c-11ea-871f-e3fccc42325c.PNG)

2019-11-28 05:12 UTC, YvesIraguha requested changes
Good morning @key-joshua, You worked on feedback I gave you. Good job. However, in test suites that you have written, you only expected on the presence of keys, make sure that you expect on the values of those keys as well. 

I addition, check and fix TravisCI. First, check if you set environment variables on your TravisCI dashboard. 

Again, remember to ignore this folder `.nyc_output/`

2019-11-28 05:12 UTC, YvesIraguha commented on test/allCreateRecordsTest.js
> +        expect(response.body).to.have.property('record');
Hello, @key-joshua please make sure that you also test the value of the field/key. Testing the presence of the key is good, but ensuring the value of the key meets expectations is better.

2019-11-28 05:12 UTC, YvesIraguha commented on test/allaSignupTest.js
> +        expect(response.body).to.be.a('object');
@key-joshua remember to test the keys/values of this `response.body`

2019-11-29 05:52 UTC, key-joshua commented
Am done with your suggested changes

2019-11-29 05:55 UTC, merged